version: '3.8'
services:
  api:
    image: insspira/api:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      - db
    networks:
      - insspira-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: agustincito100
      POSTGRES_DB: insspira
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - insspira-network
networks:
  insspira-network:
    driver: bridge
volumes:
  postgres_data: